# Generated by Django 5.2.17 on 2026-08-11 17:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('service_type', models.CharField(choices=[('annual_ad', 'Annual Ad'), ('annual_renewal', 'Annual Renewal'), ('featured', 'Featured'), ('colored_card', 'Colored Card'), ('urgent', 'Urgent'), ('extra_link', 'Extra Link'), ('extra_image', 'Extra Image'), ('ladder', 'Ladder'), ('auto_ladder', 'Automatic Ladder')], max_length=50, verbose_name='service type')),
                ('duration_days', models.PositiveIntegerField(default=365, help_text='Service duration in days', verbose_name='duration (days)')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('settings_json', models.JSONField(blank=True, default=dict, help_text='Additional tariff settings', verbose_name='settings')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'tariff',
                'verbose_name_plural': 'tariffs',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='invoice number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='subtotal')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='discount')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='ads.ad', verbose_name='ad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='unit price')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='total price')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice', verbose_name='invoice')),
            ],
            options={
                'verbose_name': 'invoice item',
                'verbose_name_plural': 'invoice items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='total amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='unit price')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='total price')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.order', verbose_name='order')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.tariff', verbose_name='tariff')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
                ('method', models.CharField(choices=[('free', 'Free'), ('online', 'Online'), ('card_to_card', 'Card to Card')], default='online', max_length=20, verbose_name='method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('manual_review', 'Manual Review')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('gateway', models.CharField(blank=True, max_length=50, verbose_name='gateway')),
                ('authority', models.CharField(blank=True, max_length=100, verbose_name='authority')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='reference ID')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('admin_note', models.TextField(blank=True, verbose_name='admin note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='ads.ad', verbose_name='ad')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoice', verbose_name='invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='billing_pay_status_f64990_idx'), models.Index(fields=['user', 'status'], name='billing_pay_user_id_562e66_idx'), models.Index(fields=['ad', 'status'], name='billing_pay_ad_id_facd43_idx')],
            },
        ),
    ]
