# Generated by Django 5.2.17 on 2026-08-15 06:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_normalized_description_hash_and_more'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='ads.ad')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ad_services', to='billing.tariff')),
            ],
            options={
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['ad', 'status', 'expires_at'], name='billing_ads_ad_id_f8df88_idx')],
            },
        ),
    ]
