# Generated by Django 5.2.17 on 2026-08-15 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_strengthen_ad_integrity'),
        ('billing', '0002_adservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('authority', ''), _negated=True), fields=('gateway', 'authority'), name='billing_unique_gateway_authority'),
        ),
    ]
