# Generated by Django 5.2.17 on 2026-08-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='سامانه آگهی', max_length=255, verbose_name='site name')),
                ('site_description', models.TextField(blank=True, verbose_name='site description')),
                ('default_meta_description', models.TextField(blank=True, verbose_name='default meta description')),
                ('logo', models.ImageField(blank=True, upload_to='settings/', verbose_name='logo')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='contact phone')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='support email')),
                ('free_ad_duration', models.PositiveIntegerField(default=30, help_text='Default duration for free ads in days', verbose_name='free ad duration (days)')),
                ('max_images', models.PositiveIntegerField(default=5, verbose_name='max images per ad')),
                ('max_links', models.PositiveIntegerField(default=5, verbose_name='max links per ad')),
                ('seo_threshold_low_views', models.PositiveIntegerField(default=10, help_text='Ads with views below this are considered low-view', verbose_name='SEO threshold for low views')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS enabled')),
                ('sms_sender_id', models.CharField(blank=True, max_length=20, verbose_name='SMS sender ID')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='maintenance mode')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='maintenance message')),
                ('header_html', models.TextField(blank=True, help_text='Custom HTML for header', verbose_name='header HTML')),
                ('footer_html', models.TextField(blank=True, help_text='Custom HTML for footer', verbose_name='footer HTML')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'site setting',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
