# Generated by Django 5.2.17 on 2026-08-11 17:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForbiddenWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='word')),
                ('normalized_word', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='normalized word')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'forbidden word',
                'verbose_name_plural': 'forbidden words',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='code')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('normalized_title', models.CharField(blank=True, db_index=True, max_length=300, verbose_name='normalized title')),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(6000)], verbose_name='description')),
                ('normalized_description', models.TextField(blank=True, verbose_name='normalized description')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords, max 11', max_length=500, verbose_name='keywords')),
                ('price', models.DecimalField(blank=True, decimal_places=0, help_text='Leave blank for "توافقی"', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('business_name', models.CharField(blank=True, max_length=255, verbose_name='business name')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('mobile_1', models.CharField(max_length=11, verbose_name='mobile 1')),
                ('show_mobile_1', models.BooleanField(default=True, verbose_name='show mobile 1')),
                ('mobile_2', models.CharField(blank=True, max_length=11, verbose_name='mobile 2')),
                ('phone_1', models.CharField(blank=True, max_length=11, verbose_name='phone 1')),
                ('phone_2', models.CharField(blank=True, max_length=11, verbose_name='phone 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('referrer', models.CharField(blank=True, max_length=255, verbose_name='referrer')),
                ('source', models.CharField(choices=[('user_panel', 'User Panel'), ('public_form', 'Public Form'), ('admin', 'Admin'), ('import', 'Import')], default='user_panel', max_length=20, verbose_name='source')),
                ('submit_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='submit IP')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('needs_permit', 'Needs Permit'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('deleted', 'Deleted')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='expires at')),
                ('sort_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='sort at')),
                ('last_ladder_at', models.DateTimeField(blank=True, null=True, verbose_name='last ladder at')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='views count')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='is featured')),
                ('is_colored', models.BooleanField(default=False, verbose_name='is colored')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='is urgent')),
                ('auto_ladder', models.BooleanField(default=False, verbose_name='auto ladder')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('slug', models.SlugField(blank=True, max_length=300, verbose_name='slug')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='taxonomy.category', verbose_name='category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='locations.city', verbose_name='city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='locations.country', verbose_name='country')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='locations.province', verbose_name='province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'ad',
                'verbose_name_plural': 'ads',
                'ordering': ['-is_featured', '-sort_at', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_thumb', models.ImageField(height_field='thumb_height', upload_to='ads/thumbs/', verbose_name='thumbnail', width_field='thumb_width')),
                ('image_display', models.ImageField(height_field='display_height', upload_to='ads/display/', verbose_name='display image', width_field='display_width')),
                ('thumb_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='thumb width')),
                ('thumb_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='thumb height')),
                ('display_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='display width')),
                ('display_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='display height')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.ad', verbose_name='ad')),
            ],
            options={
                'verbose_name': 'ad image',
                'verbose_name_plural': 'ad images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('website', 'Website'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='website', max_length=20, verbose_name='type')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='ads.ad', verbose_name='ad')),
            ],
            options={
                'verbose_name': 'ad link',
                'verbose_name_plural': 'ad links',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(blank=True, max_length=100, verbose_name='permit number')),
                ('issuer', models.CharField(blank=True, max_length=255, verbose_name='issuer')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='issued at')),
                ('image', models.ImageField(upload_to='permits/', verbose_name='permit image')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('admin_note', models.TextField(blank=True, verbose_name='admin note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permit', to='ads.ad', verbose_name='ad')),
            ],
            options={
                'verbose_name': 'ad permit',
                'verbose_name_plural': 'ad permits',
            },
        ),
        migrations.CreateModel(
            name='AdReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('no_response', 'عدم پاسخگویی'), ('fraud', 'کلاهبرداری'), ('false_info', 'خلاف واقع'), ('inappropriate', 'محتوای غیرمجاز'), ('offensive', 'محتوای نامناسب'), ('price_gouging', 'گران\u200cفروشی'), ('other', 'سایر')], max_length=20, verbose_name='reason')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('reporter_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='reporter IP')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='new', max_length=20, verbose_name='status')),
                ('admin_note', models.TextField(blank=True, verbose_name='admin note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ads.ad', verbose_name='ad')),
                ('reporter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='reporter')),
            ],
            options={
                'verbose_name': 'ad report',
                'verbose_name_plural': 'ad reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('needs_permit', 'Needs Permit'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('deleted', 'Deleted')], max_length=20, verbose_name='from status')),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('needs_permit', 'Needs Permit'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('deleted', 'Deleted')], max_length=20, verbose_name='to status')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ads.ad', verbose_name='ad')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
            ],
            options={
                'verbose_name': 'ad status history',
                'verbose_name_plural': 'ad status history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['status', 'published_at'], name='ads_ad_status_98ed00_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['status', 'category'], name='ads_ad_status_40dbaf_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['status', 'city'], name='ads_ad_status_28f610_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['category', 'city', 'status'], name='ads_ad_categor_b5b11a_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['user', 'status'], name='ads_ad_user_id_e601b1_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['expires_at', 'status'], name='ads_ad_expires_3b048d_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['is_featured', 'sort_at'], name='ads_ad_is_feat_9277ac_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['slug'], name='ads_ad_slug_35a381_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['code'], name='ads_ad_code_b28ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['normalized_title'], name='ads_ad_normali_e9a76c_idx'),
        ),
    ]
