# Generated by Django 5.2.17 on 2026-08-15 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        ('locations', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='normalized_description_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='normalized description hash'),
        ),
        migrations.AddField(
            model_name='ad',
            name='normalized_title_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='normalized title hash'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True, verbose_name='slug'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['normalized_title_hash'], name='ads_ad_normali_abbdfc_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['normalized_description_hash'], name='ads_ad_normali_1333d1_idx'),
        ),
    ]
