# Generated by Django 5.2.17 on 2026-08-15 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_normalized_description_hash_and_more'),
        ('locations', '0002_alter_city_province_alter_province_country'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['status', 'deleted_at', '-is_featured', '-sort_at', '-published_at'], name='ads_public_list_idx'),
        ),
    ]
