# Generated by Django 5.2.17 on 2026-08-15 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_postgres_trigram_indexes'),
        ('locations', '0002_alter_city_province_alter_province_country'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='phone_1',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone 1'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone 2'),
        ),
        migrations.AddConstraint(
            model_name='ad',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='ads_price_is_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='adimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('ad',), name='ads_one_primary_image_per_ad'),
        ),
    ]
