<?php if($type==='categories'): ?>
<label>عنوان<input name="title" required value="<?php echo e($record->title ?? old('title')); ?>"></label>
<label>slug<input name="slug" required value="<?php echo e($record->slug ?? old('slug')); ?>"></label>
<label>دستهٔ والد<select name="parent_id"><option value="">ندارد (گروه)</option><?php $__currentLoopData = $parents; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $parent): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($parent->id); ?>" <?php if(($record->parent_id ?? old('parent_id'))==$parent->id): echo 'selected'; endif; ?>><?php echo e($catPath[$parent->id] ?? $parent->title); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
<label>ترتیب<input type="number" name="sort_order" value="<?php echo e($record->sort_order ?? 0); ?>"></label>
<label class="wide">توضیح<textarea name="description"><?php echo e($record->description ?? old('description')); ?></textarea></label>
<label class="wide">عنوان SEO<input name="seo_title" value="<?php echo e($record->seo_title ?? old('seo_title')); ?>"></label>
<label class="wide">توضیح SEO<textarea name="seo_description"><?php echo e($record->seo_description ?? old('seo_description')); ?></textarea></label>
<?php elseif($type==='countries'): ?><label>نام<input name="name" required value="<?php echo e($record->name ?? old('name')); ?>"></label><label>slug<input name="slug" required value="<?php echo e($record->slug ?? old('slug')); ?>"></label><label>ترتیب<input type="number" name="sort_order" value="<?php echo e($record->sort_order ?? 0); ?>"></label>
<?php elseif($type==='provinces'): ?><label>کشور<select name="country_id" required><?php $__currentLoopData = $countries; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $country): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($country->id); ?>" <?php if(($record->country_id ?? old('country_id'))==$country->id): echo 'selected'; endif; ?>><?php echo e($country->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label><label>نام<input name="name" required value="<?php echo e($record->name ?? old('name')); ?>"></label><label>slug<input name="slug" required value="<?php echo e($record->slug ?? old('slug')); ?>"></label>
<?php elseif($type==='cities'): ?><label>استان<select name="province_id" required><?php $__currentLoopData = $provinces; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $province): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($province->id); ?>" <?php if(($record->province_id ?? old('province_id'))==$province->id): echo 'selected'; endif; ?>><?php echo e($province->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label><label>نام<input name="name" required value="<?php echo e($record->name ?? old('name')); ?>"></label><label>slug<input name="slug" required value="<?php echo e($record->slug ?? old('slug')); ?>"></label>
<?php elseif($type==='tariffs'): ?><label>کد<input name="code" required value="<?php echo e($record->code ?? old('code')); ?>"></label><label>عنوان<input name="title" required value="<?php echo e($record->title ?? old('title')); ?>"></label><label>قیمت (تومان)<input name="price" type="number" min="0" required value="<?php echo e($record ? round($record->price / 10) : old('price')); ?>"></label><label>نوع<select name="service_type" required><option value="ad" <?php if(($record->service_type ?? 'ad')==='ad'): echo 'selected'; endif; ?>>آگهی</option><option value="renewal" <?php if(($record->service_type ?? '')==='renewal'): echo 'selected'; endif; ?>>تمدید</option><option value="featured" <?php if(($record->service_type ?? '')==='featured'): echo 'selected'; endif; ?>>ویژه</option><option value="colored" <?php if(($record->service_type ?? '')==='colored'): echo 'selected'; endif; ?>>رنگی</option><option value="urgent" <?php if(($record->service_type ?? '')==='urgent'): echo 'selected'; endif; ?>>فوری</option><option value="ladder" <?php if(($record->service_type ?? '')==='ladder'): echo 'selected'; endif; ?>>نردبان</option><option value="auto_ladder" <?php if(($record->service_type ?? '')==='auto_ladder'): echo 'selected'; endif; ?>>نردبان خودکار</option><option value="extra_link" <?php if(($record->service_type ?? '')==='extra_link'): echo 'selected'; endif; ?>>لینک اضافه</option><option value="extra_image" <?php if(($record->service_type ?? '')==='extra_image'): echo 'selected'; endif; ?>>تصویر اضافه</option><option value="links" <?php if(($record->service_type ?? '')==='links'): echo 'selected'; endif; ?>>لینک‌ها</option><option value="promotion" <?php if(($record->service_type ?? '')==='promotion'): echo 'selected'; endif; ?>>تبلیغ در سایت‌ها</option><option value="domain" <?php if(($record->service_type ?? '')==='domain'): echo 'selected'; endif; ?>>اتصال دامین</option><option value="more_images" <?php if(($record->service_type ?? '')==='more_images'): echo 'selected'; endif; ?>>تصاویر بیشتر</option><option value="seo_keywords" <?php if(($record->service_type ?? '')==='seo_keywords'): echo 'selected'; endif; ?>>تقویت لغات کلیدی</option></select></label><label>مدت (روز)<input name="duration_days" type="number" min="1" value="<?php echo e($record->duration_days ?? old('duration_days')); ?>"></label><label class="wide">توضیح<textarea name="description"><?php echo e($record->description ?? old('description')); ?></textarea></label>
<?php else: ?><label>عبارت غیرمجاز<input name="word" required value="<?php echo e($record->word ?? old('word')); ?>"></label><?php endif; ?><label class="check"><input type="checkbox" name="is_active" value="1" <?php if($record->is_active ?? true): echo 'checked'; endif; ?>>فعال</label>
<?php /**PATH /home/hamidreza/Downloads/agahi-readme-update/resources/views/admin/catalog/fields.blade.php ENDPATH**/ ?>