<?php

declare(strict_types=1);

$root = dirname(__DIR__);
$files = [
'resources/views/user/ads/edit.blade.php' => <<<'BLADE'
@extends('layouts.app',['title'=>'ویرایش آگهی | '.config('app.name'),'robots'=>'noindex, nofollow'])
@section('content')
<section class="form-page"><h1>ویرایش آگهی</h1><p class="lead">ویرایش آگهی فعال، آن را برای بررسی مجدد ارسال می‌کند.</p><form method="post" action="{{ route('user.ads.update',$ad) }}" enctype="multipart/form-data">@csrf @method('PUT')<div class="form-grid"><label class="wide">عنوان آگهی<input name="title" value="{{ old('title',$ad->title) }}" maxlength="300" required></label><label class="wide">توضیحات<textarea name="description" maxlength="6000" rows="8" required>{{ old('description',$ad->description) }}</textarea></label><label>دسته‌بندی<select name="category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id',$ad->category_id)==$category->id)>{{ $category->title }}</option>@endforeach</select></label><label>شهر<select name="city_id" required>@foreach($cities as $city)<option value="{{ $city->id }}" @selected(old('city_id',$ad->city_id)==$city->id)>{{ $city->name }}</option>@endforeach</select></label><label>قیمت (ریال)<input type="number" name="price" min="0" value="{{ old('price',$ad->price) }}"></label><label>نام و نام خانوادگی<input name="full_name" value="{{ old('full_name',$ad->full_name) }}"></label><label>نام کسب‌وکار<input name="business_name" value="{{ old('business_name',$ad->business_name) }}"></label><label>موبایل اصلی<input name="mobile_1" value="{{ old('mobile_1',$ad->mobile_1) }}" inputmode="numeric" required></label><label>موبایل دوم<input name="mobile_2" value="{{ old('mobile_2',$ad->mobile_2) }}" inputmode="numeric"></label><label>تلفن<input name="phone_1" value="{{ old('phone_1',$ad->phone_1) }}"></label><label>ایمیل<input type="email" name="email" value="{{ old('email',$ad->email) }}"></label><label class="wide">آدرس<input name="address" value="{{ old('address',$ad->address) }}" maxlength="500"></label><label class="wide">افزودن تصویر جدید<input type="file" name="images[]" accept="image/jpeg,image/png,image/webp" multiple></label></div><div class="image-strip">@foreach($ad->images as $image)<img src="{{ $image->thumbUrl() }}" width="120" height="90" loading="lazy" alt="تصویر آگهی"></img>@endforeach</div><button class="button">ذخیرهٔ ویرایش</button></form></section>
@endsection
BLADE,
'resources/views/user/payments/index.blade.php' => <<<'BLADE'
@extends('layouts.app',['title'=>'پرداخت‌ها و سرویس‌ها | '.config('app.name'),'robots'=>'noindex, nofollow'])
@section('content')
<div class="section-heading"><div><h1>پرداخت‌ها و سرویس‌ها</h1><p class="muted">تعرفهٔ موردنظر را برای آگهی خود انتخاب کنید.</p></div><a href="{{ route('user.dashboard') }}">بازگشت به پنل</a></div>
<section class="panel"><h2>خرید یا تمدید سرویس</h2><form method="post" action="{{ route('user.payments.purchase') }}" class="form-grid">@csrf<label>آگهی<select name="ad_id" required><option value="">انتخاب آگهی</option>@foreach($ads as $ad)<option value="{{ $ad->id }}">{{ $ad->title }} — {{ $ad->status->label() }}</option>@endforeach</select></label><label>تعرفه<select name="tariff_id" required><option value="">انتخاب تعرفه</option>@foreach($tariffs as $tariff)<option value="{{ $tariff->id }}">{{ $tariff->title }} — {{ number_format($tariff->price) }} ریال</option>@endforeach</select></label><div><button class="button">ادامهٔ پرداخت</button></div></form></section>
<section><h2>فاکتورهای من</h2><div class="table-wrap"><table><thead><tr><th>شماره</th><th>آگهی</th><th>مبلغ</th><th>وضعیت</th><th>تاریخ</th></tr></thead><tbody>@forelse($invoices as $invoice)<tr><td>{{ $invoice->invoice_number }}</td><td>{{ $invoice->ad?->title ?? '—' }}</td><td>{{ number_format($invoice->total) }} ریال</td><td>{{ $invoice->status }}</td><td>{{ $invoice->created_at->format('Y/m/d') }}</td></tr>@empty<tr><td colspan="5">فاکتوری وجود ندارد.</td></tr>@endforelse</tbody></table></div>{{ $invoices->links() }}</section>
@endsection
BLADE,
'resources/views/user/profile/edit.blade.php' => <<<'BLADE'
@extends('layouts.app',['title'=>'پروفایل | '.config('app.name'),'robots'=>'noindex, nofollow'])
@section('content')
<section class="form-page"><h1>پروفایل کاربری</h1><form method="post" action="{{ route('user.profile.update') }}">@csrf @method('PUT')<div class="form-grid"><label>نام<input name="first_name" value="{{ old('first_name',auth()->user()->first_name) }}" required></label><label>نام خانوادگی<input name="last_name" value="{{ old('last_name',auth()->user()->last_name) }}" required></label><label>ایمیل<input type="email" name="email" value="{{ old('email',auth()->user()->email) }}"></label><label>نام کسب‌وکار<input name="business_name" value="{{ old('business_name',$profile?->business_name) }}"></label><label>استان<select name="province_id"><option value="">انتخاب کنید</option>@foreach($provinces as $province)<option value="{{ $province->id }}" @selected(old('province_id',$profile?->province_id)==$province->id)>{{ $province->name }}</option>@endforeach</select></label><label>شهر<select name="city_id"><option value="">انتخاب کنید</option>@foreach($cities as $city)<option value="{{ $city->id }}" @selected(old('city_id',$profile?->city_id)==$city->id)>{{ $city->name }}</option>@endforeach</select></label><label>کد پستی<input name="postal_code" value="{{ old('postal_code',$profile?->postal_code) }}"></label><label class="wide">آدرس<input name="address" value="{{ old('address',$profile?->address) }}"></label></div><button class="button">ذخیرهٔ پروفایل</button></form></section>
@endsection
BLADE,
'resources/views/user/dashboard.blade.php' => <<<'BLADE'
@extends('layouts.app',['title'=>'پنل کاربری | '.config('app.name'),'robots'=>'noindex, nofollow'])
@section('content')
<div class="section-heading"><div><h1>آگهی‌های من</h1><p class="muted">وضعیت، بازدید و عملیات مجاز آگهی‌ها را مدیریت کنید.</p></div><a class="button" href="{{ route('user.ads.create') }}">ثبت آگهی</a></div><div class="dashboard-links"><a href="{{ route('user.payments.index') }}">پرداخت‌ها و تمدید</a><a href="{{ route('user.tickets.index') }}">تیکت‌ها</a><a href="{{ route('user.profile.edit') }}">پروفایل</a></div><div class="tabs"><a class="@if(!$status)active@endif" href="{{ route('user.dashboard') }}">همه</a>@foreach(\App\Domains\Ads\Enums\AdStatus::cases() as $item)<a class="@if($status===$item->value)active@endif" href="{{ route('user.dashboard',['status'=>$item->value]) }}">{{ $item->label() }}</a>@endforeach</div><div class="table-wrap"><table><thead><tr><th>آگهی</th><th>کد</th><th>شهر</th><th>بازدید</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>@forelse($ads as $ad)<tr><td>{{ $ad->title }}</td><td>{{ $ad->code }}</td><td>{{ $ad->city?->name }}</td><td>{{ number_format($ad->views_count) }}</td><td><span class="badge">{{ $ad->status->label() }}</span></td><td><div class="row-actions">@if(!in_array($ad->status,[\App\Domains\Ads\Enums\AdStatus::Expired,\App\Domains\Ads\Enums\AdStatus::Deleted],true))<a href="{{ route('user.ads.edit',$ad) }}">ویرایش</a>@endif@if($ad->status===\App\Domains\Ads\Enums\AdStatus::Expired)<a href="{{ route('user.payments.index') }}">تمدید</a>@endif@if($ad->status===\App\Domains\Ads\Enums\AdStatus::NeedsPermit)<form method="post" action="{{ route('user.ads.permits.store',$ad) }}" enctype="multipart/form-data">@csrf<input type="file" name="image" accept="image/*"><button class="link-button">ارسال مجوز</button></form>@endif@if($ad->status!==\App\Domains\Ads\Enums\AdStatus::Deleted)<form method="post" action="{{ route('user.ads.destroy',$ad) }}" onsubmit="return confirm('آگهی حذف شود؟')">@csrf @method('DELETE')<button class="link-button danger">حذف</button></form>@endif</div></td></tr>@empty<tr><td colspan="6">آگهی‌ای وجود ندارد.</td></tr>@endforelse</tbody></table></div>{{ $ads->links() }}
@endsection
BLADE,
];
foreach ($files as $relative => $content) { $path=$root.'/'.$relative; if(!is_dir(dirname($path)) && !mkdir(dirname($path),0775,true) && !is_dir(dirname($path))) throw new RuntimeException("Cannot create {$relative}"); file_put_contents($path,$content."\n"); }
echo 'Generated '.count($files)." user completion views.\n";
