# Generated by Django 5.2.17 on 2026-08-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEORedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(db_index=True, max_length=500, verbose_name='old path')),
                ('new_path', models.CharField(max_length=500, verbose_name='new path')),
                ('status_code', models.PositiveIntegerField(default=301, help_text='HTTP status code, typically 301 for permanent redirect', verbose_name='status code')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'SEO redirect',
                'verbose_name_plural': 'SEO redirects',
                'ordering': ['-created_at'],
                'unique_together': {('old_path', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='SitemapURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, verbose_name='URL')),
                ('changefreq', models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='weekly', max_length=20, verbose_name='change frequency')),
                ('priority', models.DecimalField(decimal_places=1, default=0.5, help_text='Priority from 0.0 to 1.0', max_digits=2, verbose_name='priority')),
                ('last_modified', models.DateTimeField(blank=True, null=True, verbose_name='last modified')),
                ('is_indexable', models.BooleanField(default=True, verbose_name='is indexable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'sitemap URL',
                'verbose_name_plural': 'sitemap URLs',
                'indexes': [models.Index(fields=['is_indexable', 'last_modified'], name='seo_sitemap_is_inde_18dfe6_idx')],
            },
        ),
    ]
