# Generated by Django 5.2.17 on 2026-08-11 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='mobile')),
                ('type', models.CharField(choices=[('verification', 'Verification'), ('ad_expiry', 'Ad Expiry'), ('payment', 'Payment'), ('ticket', 'Ticket'), ('admin', 'Admin'), ('other', 'Other')], default='other', max_length=20, verbose_name='type')),
                ('provider_id', models.CharField(blank=True, max_length=100, verbose_name='provider ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('response', models.TextField(blank=True, verbose_name='response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='ads.ad', verbose_name='ad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'SMS log',
                'verbose_name_plural': 'SMS logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
