# Generated by Django 5.2.17 on 2026-08-15 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_normalized_description_hash_and_more'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='message',
            field=models.TextField(default='', verbose_name='message'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['ad', 'type', 'created_at'], name='notificatio_ad_id_20dca1_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['mobile', 'created_at'], name='notificatio_mobile_67ed21_idx'),
        ),
    ]
