# Generated by Django 5.2.17 on 2026-08-15 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_strengthen_ad_integrity'),
        ('notifications', '0002_smslog_message_smslog_notificatio_ad_id_20dca1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='attempts'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last attempt at'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='next attempt at'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['status', 'next_attempt_at'], name='notificatio_status_724247_idx'),
        ),
    ]
